### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timothoms** [SimonCoulombe/covidtwitterbot#1]
This is not an issue but a question... Thank you for posting the partial dictionary in the README here. Did you find an official dictionary for 'covid19-hist.csv' on the INSPQ site?

**Comment by SimonCoulombe** [comment]
Hi!

I haven't seen one.  I basically compared the numbers in the CSV to the numbers on INSPQ dashboard and when I found a match I knew what they meant.

**Comment by timothoms** [comment]
Thank you for your response. I feared I would have to resort to that.
